"""
Interactive Natural Language Query Interface for Data Platform Knowledge Graph.

HOW QUERYING WORKS — TWO PARALLEL TRACKS:
==========================================

TRACK 1 — Pure Graph Traversal (slash commands: /sdlc, /impact, /depends, /whochanged)
  No LLM involved. Pure Python functions that walk the NetworkX directed graph
  by following specific relationship edges. Deterministic and fast.

  Example flow for /impact col_rn_kpi_value:
    1. Find node col_rn_kpi_value in the graph
    2. Find all predecessors with edge relation = READS_FROM  → gets KPI nodes
    3. For each KPI, find predecessors with type = PowerBIDashboard → gets Dashboards
    4. Print the chain: Column → KPI → Dashboard

TRACK 2 — RAG + LLM via OpenRouter (free-text natural language questions)
  No graph queries are generated by the LLM. Instead, this uses RAG:

  Step 1 — Vector Search (ChromaDB + sentence-transformers):
    The user's question is converted to an embedding and compared against
    all node embeddings stored in ChromaDB. Top 8 similar nodes are returned.

  Step 2 — Context Building (NetworkX graph):
    For each matched node, we fetch its properties AND its graph edges
    (neighbours, incoming/outgoing relationships) from NetworkX.
    This builds a rich text context string that includes the graph structure.

  Step 3 — LLM (OpenRouter → gpt-4o-mini):
    The context string + user question is sent to the LLM.
    The LLM reads the text and answers in English.
    It does NOT generate graph queries — it reads pre-fetched graph data.

Run:
    python scripts/interactive_query.py
"""

import sys
from pathlib import Path

# Allow running directly from the project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from graph.knowledge_graph import KnowledgeGraph
from rag.vectorstore import VectorStore
from pipeline.bronze_layer import bronze_pipelines, bronze_tables, bronze_columns
from pipeline.silver_layer import silver_pipelines, silver_tables, silver_columns
from pipeline.gold_layer import gold_pipelines, gold_tables, gold_columns
from pipeline.ingestion import ingestAllData
from dictionary.data_dictionary import (
    confluencePages, jiraTickets, alerts, dataQualityRules,
    environments, powerBIDashboards, powerBIKPIs, dataDictionary
)
from utils.formatting import console, printHeader
from rich.panel import Panel
from rich.text import Text
from rag.query_engine import NaturalLanguageQueryEngine
from graph.graph_queries import (
    findFeature, showFeatureStatus, showAllFeatures,
    isFeatureInProject, queryGraphStatistics, queryKPIsByDashboard,
    queryNodeProperty
)


# =============================================================================
# Constants
# =============================================================================

EXIT_COMMANDS = {'exit', 'quit', 'q'}

FEATURE_QUESTION_KEYWORDS = {'is ', 'does ', 'has ', 'have '}
FEATURE_CONTEXT_KEYWORDS = {'part of', 'in this project', 'in the project', 'exist', 'have'}

WORDS_TO_STRIP = {
    'is', 'does', 'has', 'have', 'this', 'project', 'the', 'a', 'an',
    'part', 'of', 'exist', 'in', '?', 'feature', 'component', 'pipeline', 'table'
}

EXAMPLE_QUESTIONS = [
    "Is customer data part of this project?",
    "Is payment pluggable framework part of this project?",
    "What pipelines are related to fraud detection?",
    "Show me all Jira tickets for the order pipeline",
    "Which tables contain PII data?",
    "Show me the lineage of customer_id?",
    "What is the status of the inventory sync pipeline?",
    "What Confluence pages document the payment framework?",
    "What data quality rules are configured?",
    "Which dashboards break if the kpi_value column changes?",
    "Which KPIs depend on the pipeline_rn_gold_sales_summary pipeline?",
    "Which Jira ticket modified the rn_silver_sales dataset?",
    "What is the full data lineage from SAP Bronze to Power BI Gold?",
    "Which Power BI dashboards read from the Gold market share table?",
]

HELP_TEXT = """
================================================================================
AVAILABLE COMMANDS
================================================================================

  Natural Language Queries (Track 2 — RAG + LLM):
    Just type your question in plain English.
    The system finds relevant graph nodes via vector search, then the LLM
    reads those nodes and their relationships to answer your question.

  Feature Search Commands (Track 2 — Vector search):
    /find <feature>     - Check if a feature exists in the project
    /status <feature>   - Get full status of a feature (pipeline, tables, tickets)
    /list               - List all components in the project
    /stats              - Show knowledge graph statistics

  SDLC Impact Analysis (Track 1 — Pure graph traversal, no LLM):
    /sdlc               - Run all 3 core SDLC impact queries as a demo
    /impact <column_id> - Which dashboards/KPIs break if this column changes?
    /depends <pipeline_id> - Which KPIs depend on this pipeline?
    /whochanged <table_id> - Which Jira tickets modified this table?
    /kpis <dashboard>   - List all KPIs in a dashboard (exact, graph traversal)

  Other Commands:
    /help               - Show this help message
    exit, quit, q       - Exit the program

================================================================================
"""


# =============================================================================
# TRACK 1: SDLC Impact Analysis — pure graph traversal (no LLM required)
# =============================================================================

def columnImpactAnalysis(kg: KnowledgeGraph, columnId: str) -> None:
    """
    SDLC Query: "Which dashboards break if column X changes?"

    Traversal: Column <--[READS_FROM]-- PowerBIKPI <--[CONTAINS]-- PowerBIDashboard
    """
    printHeader(f"SDLC IMPACT: Column Change → '{columnId}'")

    if columnId not in kg.graph.nodes:
        matches = [
            nId for nId, data in kg.graph.nodes(data=True)
            if data.get('type') == 'Column'
            and columnId.lower() in (data.get('name', '') + nId).lower()
        ]
        if not matches:
            print(f"\n  Column '{columnId}' not found in graph.")
            print("  Tip: Use the column ID (e.g. col_rn_kpi_value) or part of its name.")
            return
        columnId = matches[0]

    colData = kg.graph.nodes[columnId]
    print(f"\n  Column: {colData.get('name', columnId)} (ID: {columnId})")
    print(f"  Type: {colData.get('dataType', 'N/A')} | PII: {colData.get('isPii', False)}")
    print(f"  Description: {colData.get('description', 'N/A')}\n")

    affectedKPIs = [
        sourceId for sourceId in kg.graph.predecessors(columnId)
        if kg.graph.nodes[sourceId].get('type') == 'PowerBIKPI'
        and kg.graph.get_edge_data(sourceId, columnId, {}).get('relation') == 'READS_FROM'
    ]

    definingEntries = [
        sourceId for sourceId in kg.graph.predecessors(columnId)
        if kg.graph.nodes[sourceId].get('type') == 'DataDictionaryEntry'
    ]

    if not affectedKPIs and not definingEntries:
        print("  No Power BI KPIs directly read this column.")
        return

    print("  IMPACT CHAIN:\n")

    if affectedKPIs:
        print(f"  [{len(affectedKPIs)}] Power BI KPI(s) that directly read this column:")
        affectedDashboards = set()

        for kpiId in affectedKPIs:
            kpiData = kg.graph.nodes[kpiId]
            print(f"\n    ● KPI: {kpiData.get('name', kpiId)} (ID: {kpiId})")
            print(f"      Calculation: {kpiData.get('calculation', 'N/A')}")

            dashboards = [
                sourceId for sourceId in kg.graph.predecessors(kpiId)
                if kg.graph.nodes[sourceId].get('type') == 'PowerBIDashboard'
            ]
            for dashId in dashboards:
                affectedDashboards.add(dashId)
                dashData = kg.graph.nodes[dashId]
                print(f"      → BREAKS Dashboard: {dashData.get('name', dashId)} (ID: {dashId})")
                print(f"        Workspace: {dashData.get('workspace', 'N/A')} | Owner: {dashData.get('owner', 'N/A')}")

        print(f"\n  SUMMARY: {len(affectedDashboards)} dashboard(s) at risk if '{columnId}' is renamed/removed.")

    if definingEntries:
        print("\n  Data Dictionary terms that define this column:")
        for entryId in definingEntries:
            entryData = kg.graph.nodes[entryId]
            print(f"    ● Term: {entryData.get('term', entryId)} — {entryData.get('definition', '')[:80]}...")


def pipelineDependencyAnalysis(kg: KnowledgeGraph, pipelineId: str) -> None:
    """
    SDLC Query: "Which KPIs depend on pipeline X?"

    Traversal: Pipeline --[PRODUCES]--> Table <--[READS_FROM]-- KPI <--[CONTAINS]-- Dashboard
    """
    printHeader(f"SDLC IMPACT: Pipeline Dependencies → '{pipelineId}'")

    if pipelineId not in kg.graph.nodes:
        matches = [
            nId for nId, data in kg.graph.nodes(data=True)
            if data.get('type') == 'Pipeline'
            and pipelineId.lower() in (data.get('name', '') + nId).lower()
        ]
        if not matches:
            print(f"\n  Pipeline '{pipelineId}' not found in graph.")
            return
        pipelineId = matches[0]

    pipelineData = kg.graph.nodes[pipelineId]
    print(f"\n  Pipeline: {pipelineData.get('name', pipelineId)} (ID: {pipelineId})")
    print(f"  Layer: {pipelineData.get('layer', 'N/A')} | Schedule: {pipelineData.get('schedule', 'N/A')}\n")

    producedTables = [
        targetId for targetId in kg.graph.successors(pipelineId)
        if kg.graph.nodes[targetId].get('type') == 'Table'
        and kg.graph.get_edge_data(pipelineId, targetId, {}).get('relation') == 'PRODUCES'
    ]

    if not producedTables:
        print("  This pipeline does not directly produce any tables in the graph.")
        return

    print("  Tables produced by this pipeline:")
    allAffectedKPIs = {}
    allAffectedDashboards = set()

    for tableId in producedTables:
        tableData = kg.graph.nodes[tableId]
        print(f"\n    ● Table: [{tableData.get('layer', tableData.get('schema', ''))}] {tableData.get('name', tableId)} (ID: {tableId})")

        kpisFromTable = [
            sourceId for sourceId in kg.graph.predecessors(tableId)
            if kg.graph.nodes[sourceId].get('type') == 'PowerBIKPI'
            and kg.graph.get_edge_data(sourceId, tableId, {}).get('relation') == 'READS_FROM'
        ]

        if not kpisFromTable:
            print("      No KPIs directly read from this table.")
            continue

        for kpiId in kpisFromTable:
            allAffectedKPIs[kpiId] = kg.graph.nodes[kpiId]
            kpiData = kg.graph.nodes[kpiId]
            print(f"      → KPI depends on this table: {kpiData.get('name', kpiId)} (ID: {kpiId})")

            dashboards = [
                srcId for srcId in kg.graph.predecessors(kpiId)
                if kg.graph.nodes[srcId].get('type') == 'PowerBIDashboard'
            ]
            for dashId in dashboards:
                allAffectedDashboards.add(dashId)
                dashData = kg.graph.nodes[dashId]
                print(f"         → Dashboard: {dashData.get('name', dashId)}")

    print(f"\n  SUMMARY: {len(allAffectedKPIs)} KPI(s) and {len(allAffectedDashboards)} dashboard(s) depend on this pipeline.")
    if allAffectedKPIs:
        print(f"  KPIs at risk: {', '.join(d.get('name', k) for k, d in allAffectedKPIs.items())}")


def whoChangedTable(kg: KnowledgeGraph, tableId: str) -> None:
    """
    SDLC Query: "Which Jira ticket modified dataset X?"

    Traversal: JiraTicket --[MODIFIED]--> Table
    """
    printHeader(f"SDLC AUDIT: Who Changed → '{tableId}'")

    if tableId not in kg.graph.nodes:
        matches = [
            nId for nId, data in kg.graph.nodes(data=True)
            if data.get('type') == 'Table'
            and tableId.lower() in (data.get('name', '') + nId).lower()
        ]
        if not matches:
            print(f"\n  Table '{tableId}' not found in graph.")
            return
        tableId = matches[0]

    tableData = kg.graph.nodes[tableId]
    print(f"\n  Table: [{tableData.get('layer', tableData.get('schema', ''))}] {tableData.get('name', tableId)} (ID: {tableId})")
    print(f"  Description: {tableData.get('description', 'N/A')}\n")

    modifyingTickets = [
        sourceId for sourceId in kg.graph.predecessors(tableId)
        if kg.graph.nodes[sourceId].get('type') == 'JiraTicket'
        and kg.graph.get_edge_data(sourceId, tableId, {}).get('relation') == 'MODIFIED'
    ]

    if not modifyingTickets:
        print("  No Jira tickets recorded as modifying this table.")
        return

    print(f"  [{len(modifyingTickets)}] Jira ticket(s) that modified this table:\n")
    for jiraId in modifyingTickets:
        jiraData = kg.graph.nodes[jiraId]
        statusIcon = "✓" if jiraData.get('status') == 'Done' else ("~" if jiraData.get('status') == 'In Progress' else "○")
        print(f"    [{statusIcon}] {jiraId}: {jiraData.get('summary', 'N/A')}")
        print(f"        Status: {jiraData.get('status')} | Priority: {jiraData.get('priority')} | Assignee: {jiraData.get('assignee')}")

        referencedConf = [
            targetId for targetId in kg.graph.successors(jiraId)
            if kg.graph.nodes[targetId].get('type') == 'ConfluencePage'
        ]
        if referencedConf:
            for confId in referencedConf:
                confData = kg.graph.nodes[confId]
                print(f"        Docs: [{confData.get('space')}] {confData.get('title', confId)}")
        print()


def runAllSdlcQueries(kg: KnowledgeGraph) -> None:
    """Run all three core SDLC impact queries back-to-back."""
    printHeader("SDLC AUTOMATION: Core Impact Queries")

    print("\n  These queries traverse the knowledge graph relationships to answer:")
    print("  1. Which dashboards break if a column changes?     (/impact)")
    print("  2. Which KPIs depend on a pipeline?               (/depends)")
    print("  3. Which Jira ticket modified a dataset?          (/whochanged)\n")
    print("=" * 80)

    columnImpactAnalysis(kg, "col_rn_kpi_value")
    print("\n" + "=" * 80)
    pipelineDependencyAnalysis(kg, "pipeline_rn_gold_sales_summary")
    print("\n" + "=" * 80)
    whoChangedTable(kg, "table_rn_silver_sales")


# =============================================================================
# Helper Functions
# =============================================================================

def printHelp():
    print(HELP_TEXT)


def printExamples():
    print("Example questions you can ask:")
    for question in EXAMPLE_QUESTIONS:
        print(f"  - {question}")
    print("\n" + "=" * 80 + "\n")


def loadKnowledgeGraph():
    """Initialize and populate the knowledge graph with all data."""
    kg = KnowledgeGraph()
    vectorDb = VectorStore()

    data = {
        'pipelines': bronze_pipelines + silver_pipelines + gold_pipelines,
        'tables': bronze_tables + silver_tables + gold_tables,
        'columns': bronze_columns + silver_columns + gold_columns,
        'confluencePages': confluencePages,
        'jiraTickets': jiraTickets,
        'alerts': alerts,
        'dataQualityRules': dataQualityRules,
        'environments': environments,
        'powerBIDashboards': powerBIDashboards,
        'powerBIKPIs': powerBIKPIs,
        'dataDictionary': dataDictionary
    }

    ingestAllData(kg, vectorDb, data)
    return kg, vectorDb


def extractFeatureName(userInput: str) -> str:
    words = userInput.replace('?', '').split()
    featureWords = [w for w in words if w.lower() not in WORDS_TO_STRIP]
    return ' '.join(featureWords)


def isFeatureQuestion(userInput: str) -> bool:
    lowerInput = userInput.lower()
    hasKeyword = any(kw in lowerInput for kw in FEATURE_QUESTION_KEYWORDS)
    hasContext = any(ctx in lowerInput for ctx in FEATURE_CONTEXT_KEYWORDS)
    return hasKeyword and hasContext


def handleFeatureQuestion(kg, vectorDb, userInput: str):
    featureName = extractFeatureName(userInput)
    if not featureName:
        return

    result = isFeatureInProject(kg, vectorDb, featureName)

    if result['found']:
        print(f"\n  YES - '{featureName}' is part of this project!")
        print(f"\n  Found {result['matchCount']} related items:")
        for match in result['matches'][:3]:
            print(f"    - [{match['type']}] {match['name']}")
        print(f"\n  Use '/status {featureName}' for full status.")
    else:
        print(f"\n  NO - '{featureName}' was not found in this project.")
        print("\n  Try different keywords or use '/list' to see all components.")


# =============================================================================
# Command Handler
# =============================================================================

class CommandHandler:
    def __init__(self, kg, vectorDb, queryEngine):
        self.kg = kg
        self.vectorDb = vectorDb
        self.queryEngine = queryEngine

    def handle(self, userInput: str) -> bool:
        if not userInput:
            return True
        if userInput.lower() in EXIT_COMMANDS:
            print("\nGoodbye!")
            return False

        if userInput.startswith('/'):
            self._handleSlashCommand(userInput)
        elif isFeatureQuestion(userInput):
            handleFeatureQuestion(self.kg, self.vectorDb, userInput)
        else:
            self._handleNaturalLanguageQuery(userInput)

        return True

    def _handleSlashCommand(self, userInput: str):
        command = userInput.lower()

        if command == '/help':
            printHelp()
        elif command == '/list':
            showAllFeatures(self.kg)
        elif command == '/stats':
            queryGraphStatistics(self.kg)
        elif command == '/sdlc':
            runAllSdlcQueries(self.kg)
        elif command.startswith('/impact '):
            columnId = userInput[8:].strip()
            if columnId:
                columnImpactAnalysis(self.kg, columnId)
            else:
                print("\n  Usage: /impact <column_id>  (e.g. /impact col_rn_kpi_value)")
        elif command.startswith('/depends '):
            pipelineId = userInput[9:].strip()
            if pipelineId:
                pipelineDependencyAnalysis(self.kg, pipelineId)
            else:
                print("\n  Usage: /depends <pipeline_id>")
        elif command.startswith('/whochanged '):
            tableId = userInput[12:].strip()
            if tableId:
                whoChangedTable(self.kg, tableId)
            else:
                print("\n  Usage: /whochanged <table_id>")
        elif command.startswith('/find '):
            featureName = userInput[6:].strip()
            if featureName:
                findFeature(self.kg, self.vectorDb, featureName)
            else:
                print("\n  Usage: /find <feature name>")
        elif command.startswith('/status '):
            featureName = userInput[8:].strip()
            if featureName:
                showFeatureStatus(self.kg, self.vectorDb, featureName)
            else:
                print("\n  Usage: /status <feature name>")
        elif command.startswith('/kpis '):
            dashboardName = userInput[6:].strip()
            if dashboardName:
                queryKPIsByDashboard(self.kg, dashboardName)
            else:
                print("\n  Usage: /kpis <dashboard name or id>  (e.g. /kpis Reckitt Nutrition Executive)")
        else:
            print(f"\n  Unknown command: {userInput}")
            print("  Type /help for available commands.")

    def _handleNaturalLanguageQuery(self, userInput: str):
        import re
        lower = userInput.lower()

        # Detect "which KPIs are in dashboard X" — route to graph traversal
        if any(kw in lower for kw in ('kpi', 'kpis')) and \
           any(kw in lower for kw in ('dashboard', 'report')):
            quoted = re.search(r'["\'](.+?)["\']', userInput)
            if quoted:
                dashboardName = quoted.group(1)
            else:
                match = re.search(r'dashboard\s+(.+)', userInput, re.IGNORECASE)
                dashboardName = match.group(1).strip('?').strip() if match else userInput
            queryKPIsByDashboard(self.kg, dashboardName)
            return

        # Detect property lookups — "what are the tags/linkedPipelines/linkedConfluence for X"
        PROPERTY_KEYWORDS = {
            'tag': 'tags',
            'linkedpipeline': 'linkedPipelines',
            'linked pipeline': 'linkedPipelines',
            'linkedconfluence': 'linkedConfluence',
            'linked confluence': 'linkedConfluence',
        }
        for kw, prop in PROPERTY_KEYWORDS.items():
            if kw in lower:
                quoted = re.search(r'["\'](.+?)["\']', userInput)
                # Also match bare ticket IDs like DATA-111
                ticket = re.search(r'\b([A-Z]+-\d+)\b', userInput)
                entityName = quoted.group(1) if quoted else (ticket.group(1) if ticket else None)
                if entityName:
                    queryNodeProperty(self.kg, entityName, prop)
                    return

        console.print("\n[bold cyan]Searching knowledge graph...[/bold cyan]")
        answer = self.queryEngine.query(self.kg, self.vectorDb, userInput)
        console.print(Panel(answer, title="[bold green]ANSWER[/bold green]",
                            border_style="green", padding=(1, 2)))


# =============================================================================
# Main Entry Point
# =============================================================================

def main():
    console.print("\n[bold cyan]DATA PLATFORM KNOWLEDGE GRAPH[/bold cyan]  [dim]Interactive Query Interface[/dim]")
    console.print("[dim]Initializing knowledge graph...[/dim]\n")

    kg, vectorDb = loadKnowledgeGraph()
    console.print("[bold green]Knowledge graph loaded.[/bold green] Type [cyan]/help[/cyan] for commands or ask a question.\n")

    console.print("[bold white]Example questions you can ask:[/bold white]")
    for q in EXAMPLE_QUESTIONS:
        console.print(f"  [dim]-[/dim] [cyan]{q}[/cyan]")
    console.print()

    queryEngine = NaturalLanguageQueryEngine()
    handler = CommandHandler(kg, vectorDb, queryEngine)

    while True:
        try:
            userInput = input("Your question: ").strip()
            if not handler.handle(userInput):
                break
        except KeyboardInterrupt:
            console.print("\n[dim]Goodbye![/dim]")
            break
        except Exception as e:
            console.print(f"\n[red]Error:[/red] {e}")


if __name__ == "__main__":
    main()
